### ISSUE TITLE
Discussion of Berti 2019 & Filosa 2020

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#5] opened 2020-10-20 11:38 UTC
* Monica Berti (2019). "Historical Fragmentary Texts in the Digital Age." In ed. Berti, _Digital Classical Philology: Ancient Greek and Latin in the Digital Revolution_, pp. 257–276. Available: https://doi.org/10.1515/9783110599572-015
* Martina Filosa & Alessio Sopracasa (2020). "Encoding Byzantine Seals: SigiDoc." In _Proceedings of the 9th Conference of AIUCD (15-17 January, 2020)._ Available: https://aiucd2020.unicatt.it/aiucd-Sopracasa_Filosa.pdf

Some starting questions:
1. Who are the authors, what is their relationship to their subject matter, and how might this impact how we read their papers?
1. How do these two approaches to encoding ancient texts differ? Are some of these differences because of genre, medium, discipline, technical interests, or other things?
1. Does either paper add new perspectives to the discussion of standards vs custom schemas that came up in last week's session?
1. How far do new technical approaches lead to or imply new or better research questions (in these projects, or generally)?

**Comment by HLBallard44** [comment] 2020-10-21 18:07
Monica Berti (2019). "Historical Fragmentary Texts in the Digital Age."

- the focus of this article: how the digital revolution has changed the way scholars assess and represent fragmentary texts while "preserving the editorial and philological traditions."
- Digital Classical philology has two challenges: 
1. converting printed editions of Greek and Latin sources into digital editions while keeping their textual and editorial heritage, which is what the "first generation" accomplished
2. the "second generation" focuses on "publishing multiple editions of the same work, reproduce the critical apparatus and all other paratextual elements (prefaces, introductions,
indexes, bibliographies, notes, etc.), and generate collaborative environments
for critical editing of Greek and Latin sources" (p.261)
- Two project examples are The Digital Fragmenta Historicorum Graecorum (DFHG) and the Digital Athenaeus
1. The purpose of the DFHG is to provide "textual, philological, and computational methods" to represent texts in a digital setting and fragmentary authors not only in Greek and Latin but also in other collections.
2. Digital Athenaeus provides scholars with the means to access Deipnosophists (and other authors and works cited by Athenaeus) and procure specific information by "implementing a data model for identifying, analyzing, and citing instances of text reuse in the Deipnosophists." (p. 270)
- These projects present the advantages of having Classical sources digitized while also reflecting upon the challenges and issues that still need to be addressed.

**Comment by nicolealexandra33** [comment] 2020-10-23 07:11
Not sure if my Q3 answer is totally correct/sufficient, so please feel free to correct me:
1.	Monica Berti is a digital classist who focuses on the Computational Analysis of Ancient Greek and Latin; one of Alessio Sopracasa’s focuses has been on encoding Byzantine seals, as is Martina Filosa’s
2.	Regarding the digitisation of Greek and Latin texts, Berti emphasises the importance of digitising fragments as well as surviving works of lesser known authors. In Sopracasa and Filosa’s article, there is a greater emphasis on following and recording the provenance of the seals as many are sold in auctions or collected in private collections. 
3.	Berti: texts converted to OCR; also has citations attached and linked to the Uniform Resource Name, hyperlinks to geographic names and proper names; Sopracasa and Filosa: they use SigiDoc, based on EpiDoc which uses a subset of the TEI standard. Based on Sopracasa and Filosa’s article, there is much more of a push for standardisation of Byzantine seals using SidiDocs.
4.	Classics: much more efficient searches for terms, as well as a spread of terms and texts across time periods and geographically, also greater understanding of lesser known authors

**Comment by LauraHead** [comment] 2020-10-23 15:46
Regarding the suggested q3 and q4, I feel the Berti article in particular highlights the benefits of using a standard schema within a field, so as to allow easy and comprehensive comparison and collation of inscriptions as evidenced in the exemplar projects she provides. This then seems to demonstrate that such digital projects as the Athenaeus example do open up new research avenues by significantly reducing the labour involved in searching for references etc. and other such enquiries across a large collection of texts.

**Comment by despinaborcea** [comment] 2020-10-24 10:49
**Q1.** Alessio Sopracasa is a History Faculty member of the University of Paris-Sorbonne and Martina Filosa is based at the University of Cologne, in the Department of Byzantine and Modern Greek Studies. The article is focused on assessing the role of SigiDoc in digitizing Byzantine seals, as well as publications on this subject. The fact that both authors are experts in the field of Byzantine sigillography foreshadows a very focused approach on this particular topic. 

**Q2.** While Berti deals with ancient fragmentary works, Sopracasa and Filosa look at more recent material (as stated in their article, between the 4th and 15th century AD). Because they handle different materials, the approaches are bound to be different. For example, Berti’s article is focused on texts (and therefore words), while Byzantine seals require an iconographic approach (because they contain ‘images’).

**Comment by despinaborcea** [comment] 2020-10-24 10:51
I found Hannah's summary comprehensive and for this reason I did not include Berti's article in the answer for the 1st question!

**Comment by chiaradimaio** [comment] 2020-10-24 17:50
Both articles show how a digital scholarly approach has implemented knowledge and availability of information about ancient texts. However, there is a crucial difference between the approach a Classicist and a Byzantinist could have towards their subject (as usually happens in non-digital editions). The projects mentioned in Monica Berti’s article focus on largely studied topics, i.e. the fragments of Greek historians and Athaeneus. The existence of an established philological tradition prepares the digitization, which also aims at preserving those previous studies, in order to make them reusable and reliable, in a collaborative context. 
On the other hand, the SigiDoc project deals with a ‘great amount of unpublished material’: this leads to an even more interesting perspective, since the study on Byzantine seals is following a computational direction and its promoters are creating a completely new discipline. In fact, this project involves historical, iconographical and material references, that lead to a ‘high customization of EFES’ and make it a unique work in the field of text encoding.

**Comment by Kiamanx** [comment] 2020-10-24 19:52
### Martina Filosa & Alessio Sopracasa (2020). "Encoding Byzantine Seals: SigiDoc." In Proceedings of the 9th Conference of AIUCD (15-17 January, 2020)

1. **Alessio Sopracasa** is faculty at the Paris-Sarbonne University and **Martina Filosa** is in the department of Byzantine and Modern
Greek Studies at the University of Cologne. Both are sphragists and have published numerous papers on Byzantine sigillography in the past, this is their first published collaboration relating to SigiDoc. This paper was written to coincide with both the "Digitizing & Encoding Seals: SigiDoc and RTI-Dome in action" workshop being hosted by both academics and the AIUCD annual conference. The article in question is meant to report on the current status of the SigiDoc program during the time of writing.
2. The two articles differ due to the fundamental subject matter of each. Berti's article has a focus on fragmentary texts and the methods of adapting Classical philology whilst 'preserving traditions', using the DFHG and Digital Athenaeus as examples of digitally adapted philology. Filosa & Sopracasa embrace SigiDoc fully and claim that its existence provides an immortal archive of the document in question:
_"The preservation history of the seal is a major concern, not only in establishing which is the current repository of a seal, but also in being able to follow it through its different displacements, which is of the utmost importance especially when the seal enters a private collection or is sold in an auction - thanks to SigiDoc it will be easier to follow them before they disappear in private collections."_
Both articles end with an optimistic outlook for the future of their respective mediums. With an online digital archive of these materials, they become permanent and not subject to the constant hands-changing of artefacts.
3. Filosa & Sopracasa mention that SigiDoc is revolutionary as a standardised schema for digitised Byzantine seals. They mention that the format had been merged with the EpiDoc template which allowed for straightforward writing up of an artefacts' information. The paramount purpose of the standardised schema is to create a database that can be easily accessed by academics. By merging with EpiDoc, the database also conforms to the standardised system for digital classical artefact recording. Accessibility is one of the main goals that Filosa & Sopracasa set out for when creating SigiDoc.

**Comment by Kiamanx** [comment] 2020-10-24 19:53
I tried not to step on anyones toes and also not go on for too long during this. It seems a lot of the points I would have made have already been said but I hope that I have given at least a semi-accurate commentary of this article.

**Comment by nicolealexandra33** [comment] 2020-10-25 16:14
Not sure I can contribute much more since everyone had some really salient points, but Kiarash's Q2 regarding following Byzantine seals before they disappear into private collections is arguably also relevant to Q4 regarding new research questions

**Comment by chiaradimaio** [comment] 2020-10-26 11:03
With regard to Q4, I think that a work such as Sopracasa and Filosa's one could lead to new outcomes for Classicists as well. History of classical scholarship has too often shown more interest in the text itself than in its material vehicles. This has lead to the loss or the deperishment of papiry and manuscripts, of which we only have photographies or diplomatic copies, in the luckiest cases. Encoding texts should mean, for a papyrologist and a diplomatist as well, taking into account the material and iconographic aspect, which is something that the traditional apparatus criticus can only do in an indirect way, with the display of large circumlocutions that do not help visualizing the real condition of the support.

**Comment by HLBallard44** [comment] 2020-10-26 17:57
When comparing the two articles, could it be said that Berti focuses more on EFES enhancing the research of philology and papyrology while Filosa and Sopracasa concentrate on material objects with writing and how SigiDoc will aid in analyzing them? 
The main thing I noticed between the two articles is the medium they are studying. Most of what we have discussed with EFES, and what Berti discusses in her article, has to do with fragmentary texts and philology. Filosa and Sopracasa associate SigiDoc with an artifact/ material object: the Byzantine seals. 
Does changing the medium of what we study affect how we use EFES/EpiDoc?

**Comment by LauraHead** [comment] 2020-10-26 18:03
Not sure I have too much more to add to everyone’s observations, but reading others’ responses highlighting the unique challenges that the Byzantine seals project has in terms of dealing with unpublished and iconographic material has clarified why custom schemas have perhaps more value when used in projects that are not already built on a long, non-digitised scholarly tradition, such as philology, as I think Chiara and Kiarash have pointed out.

**Comment by despinaborcea** [comment] 2020-10-27 09:09
For Q4, I would argue that new technologies, both in these cases, as well as in the sphere of Classics in general would bring in the advantage of accessibility for scholars. Even if a particular project is not concerned with the entirety of a collection of say, papyri, having easy access to all the materials from that collection would enable a classicist to have a broad overview of the material 'context' for a particular papyrus. I tried not to reiterate everyone else's answers!

**Closed as completed** 2021-01-11 18:08 UTC
Labels: discussion, ICS02
